@extends('layouts.app')
@section('title', 'Overview')
@section('content')
<div class="mx-auto max-w-7xl">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div><p class="text-sm font-semibold text-violet-600">Operations overview</p><h1 class="mt-1 text-3xl font-black tracking-tight text-slate-950">Central Support</h1><p class="mt-2 text-sm text-slate-500">Monitor every connected EcclesiaOS installation from one place.</p></div>
        <div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">● API service online</div>
    </div>
    @if(session('status'))<div class="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
    @if(session('error'))<div class="mt-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ session('error') }}</div>@endif
    @if(session('installation_token'))<div class="mt-4 rounded-2xl border border-amber-300 bg-amber-50 p-5"><p class="text-sm font-bold text-amber-900">Copy this installation token now</p><code class="mt-3 block overflow-x-auto rounded-xl bg-white px-4 py-3 text-sm text-slate-800">{{ session('installation_token') }}</code><p class="mt-2 text-xs text-amber-800">It cannot be displayed again. Add it to that church’s Central Connection settings.</p></div>@endif

    <div class="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Connected installations',$stats['installations'],'radio'],['Active in 24 hours',$stats['active_today'],'activity'],['Events received',$stats['events'],'inbox'],['Questions to review',$stats['questions'],'message-circle']] as $stat)<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="text-sm text-slate-500">{{ $stat[0] }}</div><div class="mt-3 text-3xl font-black">{{ $stat[1] }}</div><div class="mt-2 text-xs font-semibold text-violet-600">{{ $stat[2] }}</div></div>@endforeach</div>

    <div class="mt-8 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="font-black">Connected installations</h2><p class="mt-1 text-sm text-slate-500">Each church uses its own revocable token.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-600">{{ $installations->count() }} total</span></div><div class="mt-5 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th class="pb-3">Church</th><th class="pb-3">Version</th><th class="pb-3">Last seen</th><th class="pb-3">Status</th><th></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($installations as $installation)<tr><td class="py-4 font-semibold">{{ $installation->church_name ?: 'Unnamed church' }}<div class="text-xs font-normal text-slate-400">{{ $installation->installation_id }}</div></td><td class="py-4 text-slate-500">{{ $installation->version ?: '—' }}</td><td class="py-4 text-slate-500">{{ $installation->last_seen_at?->diffForHumans() ?: 'Never' }}</td><td class="py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $installation->enabled ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $installation->enabled ? 'Enabled' : 'Disabled' }}</span></td><td class="py-4 text-right"><form method="POST" action="{{ route('installations.toggle', $installation) }}">@csrf @method('PATCH')<button class="text-xs font-bold text-violet-600">{{ $installation->enabled ? 'Disable' : 'Enable' }}</button></form></td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-sm text-slate-500">No churches connected yet.</td></tr>@endforelse</tbody></table></div></section>
    <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Connect a church</h2><p class="mt-1 text-sm leading-6 text-slate-500">Create a token and give it to the church administrator securely.</p><form method="POST" action="{{ route('installations.token') }}" class="mt-5 space-y-4">@csrf<label class="block text-sm font-semibold">Installation ID<input name="installation_id" required placeholder="church-a-production" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"></label><label class="block text-sm font-semibold">Church name<input name="church_name" required placeholder="Example Church" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"></label><button class="w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-bold text-white hover:bg-violet-700">Create installation token</button></form></section></div>

    <div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Recent events</h2><div class="mt-4 divide-y divide-slate-100">@forelse($events as $event)<div class="py-3"><div class="flex justify-between gap-3 text-sm font-semibold"><span>{{ $event->event_type }}</span><span class="text-xs font-normal text-slate-400">{{ $event->created_at->diffForHumans() }}</span></div><div class="mt-1 text-xs text-slate-500">{{ $event->installation_id }}</div></div>@empty<p class="py-5 text-sm text-slate-500">No events received yet.</p>@endforelse</div></section><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-black">Community questions</h2><div class="mt-4 divide-y divide-slate-100">@forelse($questions as $question)<div class="py-3"><div class="font-semibold">{{ $question->title }}</div><div class="mt-1 text-xs text-slate-500">{{ $question->category }} · {{ $question->status }}</div></div>@empty<p class="py-5 text-sm text-slate-500">No community questions yet.</p>@endforelse</div></section></div>
</div>
@endsection
