@extends('layouts.app')
@section('title', $ticket->reference)
@section('content')
<div class="mx-auto max-w-7xl">
    <div class="flex flex-wrap items-center justify-between gap-3"><a href="{{ route('support.tickets') }}" class="text-sm font-semibold text-violet-600 hover:text-violet-800">← Back to ticket queue</a><div class="flex items-center gap-3"><span class="font-mono text-xs font-semibold text-slate-500">{{ $ticket->reference }}</span><form method="POST" action="{{ route('support.tickets.delete', $ticket) }}" onsubmit="return confirm('Delete this ticket permanently?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600 hover:text-rose-800">Delete ticket</button></form></div></div>
    @if(session('status'))<div class="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mt-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
    <div class="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
        <main class="min-w-0 space-y-6">
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 bg-gradient-to-br from-violet-50 to-white px-6 py-7"><div class="flex flex-wrap items-center gap-2"><span class="rounded-full bg-violet-100 px-3 py-1 text-xs font-semibold text-violet-700">{{ $ticket->installation_id }}</span><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $ticket->priority === 'urgent' ? 'bg-rose-50 text-rose-700' : 'bg-slate-100 text-slate-600' }}">{{ str($ticket->priority)->headline() }} priority</span></div><h1 class="mt-4 text-2xl font-semibold tracking-tight text-slate-950">{{ $ticket->subject }}</h1><p class="mt-2 text-xs text-slate-500">Opened {{ $ticket->created_at->format('M d, Y · H:i') }} · {{ $ticket->requester['name'] ?? 'EcclesiaOS' }}</p></div><div class="px-6 py-6"><p class="whitespace-pre-wrap text-sm leading-7 text-slate-700">{{ $ticket->body }}</p>@if($ticket->expected_outcome || $ticket->page_url)<div class="mt-6 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-2">@if($ticket->expected_outcome)<div><p class="text-[11px] font-semibold uppercase text-slate-400">Expected outcome</p><p class="mt-1 text-sm text-slate-700">{{ $ticket->expected_outcome }}</p></div>@endif @if($ticket->page_url)<div><p class="text-[11px] font-semibold uppercase text-slate-400">Reported page</p><p class="mt-1 truncate text-sm text-violet-600">{{ $ticket->page_url }}</p></div>@endif</div>@endif</div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-base font-semibold">Conversation and follow-up</h2><p class="mt-1 text-xs text-slate-500">Keep the church informed from this single timeline.</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500">{{ $ticket->replies->count() }} replies</span></div><div class="mt-6 space-y-4">@forelse($ticket->replies->sortBy('created_at') as $reply)<div class="rounded-xl border {{ $reply->is_internal ? 'border-amber-200 bg-amber-50' : 'border-slate-100 bg-slate-50' }} p-4"><div class="flex flex-wrap items-center justify-between gap-2"><span class="text-sm font-semibold text-slate-800">{{ data_get($reply->author, 'name', 'Support') }} @if($reply->is_internal)<span class="ml-1 text-xs font-normal text-amber-700">· Internal note</span>@endif</span><span class="text-[11px] text-slate-400">{{ $reply->created_at->diffForHumans() }}</span></div><p class="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{{ $reply->body }}</p></div>@empty<div class="rounded-xl border border-dashed border-slate-200 px-5 py-8 text-center text-sm text-slate-500">No follow-up messages yet.</div>@endforelse</div><form method="POST" action="{{ route('support.tickets.replies.store', $ticket) }}" class="mt-6 border-t border-slate-100 pt-5">@csrf<label class="text-sm font-semibold text-slate-700">Send a follow-up<textarea name="body" required rows="5" placeholder="Write a clear update for the church..." class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"></textarea></label><div class="mt-3 flex flex-wrap items-center justify-between gap-3"><label class="flex items-center gap-2 text-xs text-slate-500"><input type="checkbox" name="is_internal" value="1" class="rounded text-violet-600"> Internal note only</label><button class="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold text-white hover:bg-violet-700">Send follow-up</button></div></form></section>
        </main>
        <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><h2 class="text-base font-semibold">Ticket update</h2><p class="mt-1 text-xs text-slate-500">Change status and sync EcclesiaOS.</p></div><span class="size-2 rounded-full {{ in_array($ticket->status, ['resolved','closed'], true) ? 'bg-emerald-500' : 'bg-violet-500' }}"></span></div><form method="POST" action="{{ route('support.tickets.update', $ticket) }}" class="mt-6 space-y-4">@csrf @method('PATCH')<label class="block text-xs font-semibold text-slate-600">Subject<input name="subject" value="{{ $ticket->subject }}" required class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"></label><label class="block text-xs font-semibold text-slate-600">Status<select name="status" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm">@foreach(['new','triaged','in_progress','waiting_on_church','resolved','closed'] as $status)<option value="{{ $status }}" @selected($ticket->status === $status)>{{ str($status)->headline() }}</option>@endforeach</select></label><label class="block text-xs font-semibold text-slate-600">Priority<select name="priority" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm">@foreach(['low','normal','high','urgent'] as $priority)<option value="{{ $priority }}" @selected($ticket->priority === $priority)>{{ str($priority)->headline() }}</option>@endforeach</select></label><label class="block text-xs font-semibold text-slate-600">Original issue<textarea name="body" required rows="8" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm leading-6">{{ $ticket->body }}</textarea></label><button class="w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-800">Save and sync ticket</button></form><div class="mt-6 border-t border-slate-100 pt-5"><p class="text-[11px] font-semibold uppercase text-slate-400">Delivery guidance</p><p class="mt-2 text-xs leading-5 text-slate-500">Saving the ticket sends the status and content update to the connected EcclesiaOS installation.</p></div></aside>
    </div>
</div>
@endsection
