@extends('layouts.app')

@section('title', 'Support Tickets')

@section('content')
<div class="mx-auto max-w-7xl">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-wide text-violet-600">Support operations</p><h1 class="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Support tickets</h1><p class="mt-2 text-sm text-slate-500">Triage church requests, open a focused workspace, and keep every follow-up in one conversation.</p></div><a href="#new-ticket" class="rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white shadow-sm hover:bg-violet-700">New ticket</a></div>
    @if(session('status'))<div class="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mt-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
    <div class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Open tickets',$stats['open'],'Needs attention','text-violet-600'],['Urgent',$stats['urgent'],'Priority queue','text-rose-600'],['Waiting on church',$stats['waiting'],'Follow up needed','text-amber-600'],['Resolved',$stats['resolved'],'Completed support','text-emerald-600']] as $stat)<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{ $stat[0] }}</p><div class="mt-3 flex items-end justify-between"><span class="text-2xl font-semibold text-slate-950">{{ number_format($stat[1]) }}</span><span class="text-xs font-semibold {{ $stat[3] }}">{{ $stat[2] }}</span></div></div>@endforeach</div>
    <form method="GET" class="mt-7 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_190px_auto_auto]"><input name="q" value="{{ request('q') }}" placeholder="Search ticket, church, or subject" class="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"><select name="status" class="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"><option value="">All statuses</option>@foreach(['new','triaged','in_progress','waiting_on_church','resolved','closed'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ str($status)->headline() }}</option>@endforeach</select><button class="rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Filter</button>@if(request()->hasAny(['q','status']))<a href="{{ route('support.tickets') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-center text-sm font-semibold text-slate-600">Clear</a>@endif</form>
    <div class="mt-7 grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 bg-slate-50 px-6 py-4"><div><h2 class="text-base font-semibold">Ticket queue</h2><p class="mt-1 text-xs text-slate-500">Select a ticket to open its support workspace.</p></div><span class="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-500">{{ $tickets->total() }} total</span></div><div class="divide-y divide-slate-100">
            @forelse($tickets as $ticket)<a href="{{ route('support.tickets.show', $ticket) }}" class="block px-6 py-5 transition hover:bg-violet-50/40"><div class="flex flex-wrap items-start justify-between gap-3"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="font-mono text-xs font-semibold text-violet-700">{{ $ticket->reference }}</span><span class="rounded-full px-2 py-1 text-[10px] font-semibold {{ $ticket->priority === 'urgent' ? 'bg-rose-50 text-rose-700' : ($ticket->priority === 'high' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600') }}">{{ str($ticket->priority)->headline() }}</span></div><h3 class="mt-2 truncate text-sm font-semibold text-slate-900">{{ $ticket->subject }}</h3><p class="mt-1 truncate text-xs text-slate-500">{{ $ticket->installation_id }} · {{ $ticket->replies_count }} {{ str('reply')->plural($ticket->replies_count) }}</p></div><div class="text-right"><span class="rounded-full px-2.5 py-1 text-[10px] font-semibold {{ in_array($ticket->status, ['resolved','closed'], true) ? 'bg-emerald-50 text-emerald-700' : ($ticket->status === 'waiting_on_church' ? 'bg-amber-50 text-amber-700' : 'bg-violet-50 text-violet-700') }}">{{ str($ticket->status)->headline() }}</span><p class="mt-2 text-[11px] text-slate-400">{{ $ticket->created_at->diffForHumans() }}</p></div></div></a>@empty<div class="px-6 py-14 text-center"><p class="font-semibold text-slate-700">No tickets found</p><p class="mt-1 text-sm text-slate-500">New EcclesiaOS submissions will appear here after synchronization.</p></div>@endforelse
        </div><div class="border-t border-slate-100 px-6 py-4">{{ $tickets->links() }}</div></section>
        <section id="new-ticket" class="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-start gap-3"><span class="grid size-9 place-items-center rounded-xl bg-violet-50 text-lg text-violet-600">+</span><div><h2 class="text-base font-semibold">Create a ticket</h2><p class="mt-1 text-xs leading-5 text-slate-500">Start a support request for a connected church.</p></div></div><form method="POST" action="{{ route('support.tickets.store') }}" class="mt-6 space-y-3">@csrf<input name="installation_id" required placeholder="Installation ID" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"><input name="subject" required placeholder="Subject" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"><textarea name="body" required rows="5" placeholder="Describe the issue and expected outcome" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"></textarea><select name="priority" class="w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm"><option value="normal">Normal priority</option><option value="low">Low priority</option><option value="high">High priority</option><option value="urgent">Urgent priority</option></select><button class="w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white hover:bg-violet-700">Create ticket</button></form></section>
    </div>
</div>
@endsection
