<form method="POST" action="{{ $action }}" class="mt-7 space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
    @csrf @if($method !== 'POST') @method($method) @endif
    @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"><p class="font-bold">Please correct the following:</p><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div><label for="title" class="text-sm font-bold text-slate-700">Title</label><input id="title" name="title" required maxlength="180" value="{{ old('title', $article->title ?? '') }}" placeholder="Example: How to reset your password" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100"></div>
    <div><label for="category" class="text-sm font-semibold text-slate-700">Category</label><select id="category" name="category" required class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100"><option value="">Choose a category</option>@foreach($categories as $category)<option value="{{ $category->name }}" @selected(old('category', $article->category ?? '') === $category->name)>{{ $category->name }}</option>@endforeach</select></div>
    <div><label for="body" class="text-sm font-bold text-slate-700">Article content</label><p class="mt-1 text-xs text-slate-500">Use plain text with headings and numbered steps for easy reading.</p><textarea id="body" name="body" required rows="20" maxlength="50000" placeholder="Write the complete support guidance here..." class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-mono text-sm leading-6 outline-none focus:border-violet-400 focus:ring-2 focus:ring-violet-100">{{ old('body', $article->body ?? '') }}</textarea></div>
    <label class="flex items-start gap-3 rounded-xl bg-slate-50 p-4 text-sm"><input type="checkbox" name="published" value="1" @checked(old('published', $article->published ?? false)) class="mt-0.5 rounded text-violet-600"><span><span class="block font-bold text-slate-800">Publish this article</span><span class="mt-1 block text-xs text-slate-500">Published articles are available to connected EcclesiaOS installations through the support API.</span></span></label>
    <div class="flex flex-wrap justify-end gap-3 border-t border-slate-100 pt-5"><a href="{{ isset($article) && $article->exists ? route('support.knowledge.show', $article) : route('support.knowledge') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-600">Cancel</a><button class="rounded-xl bg-violet-600 px-5 py-3 text-sm font-black text-white hover:bg-violet-700">{{ $button }}</button></div>
</form>
