@extends('layouts.app')
@section('title', 'Knowledge Categories')
@section('content')
<div class="mx-auto max-w-7xl">
    <div class="flex flex-wrap items-end justify-between gap-4"><div><a href="{{ route('support.knowledge') }}" class="text-sm font-semibold text-violet-600 hover:text-violet-800">← Knowledge Base</a><h1 class="mt-4 text-3xl font-semibold text-slate-950">Knowledge categories</h1><p class="mt-2 text-sm text-slate-500">Organize support articles into clear groups for churches and members.</p></div></div>
    @if(session('status'))<div class="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mt-6 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
    <div class="mt-7 grid gap-6 xl:grid-cols-[.7fr_1.3fr]">
        <form method="POST" action="{{ route('support.knowledge.categories.store') }}" class="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">@csrf<h2 class="text-base font-semibold">Create category</h2><p class="mt-1 text-sm text-slate-500">Add a reusable group for future articles.</p><label class="mt-5 block text-sm font-medium text-slate-700">Category name<input name="name" required maxlength="80" value="{{ old('name') }}" placeholder="Example: Account Help" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm"></label><button class="mt-4 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white hover:bg-violet-700">Create category</button></form>
        <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 bg-slate-50 px-6 py-4"><div><h2 class="text-base font-semibold">All categories</h2><p class="mt-1 text-xs text-slate-500">{{ $categories->count() }} categories available</p></div><a href="{{ route('support.knowledge.create') }}" class="text-sm font-semibold text-violet-600 hover:text-violet-800">New article</a></div><div class="divide-y divide-slate-100">
            @forelse($categories as $category)<div class="grid gap-4 px-6 py-5 md:grid-cols-[1fr_110px_230px] md:items-center"><div><div class="font-semibold text-slate-900">{{ $category->name }}</div><div class="mt-1 text-xs text-slate-400">{{ $category->slug }}</div></div><div class="text-sm text-slate-500">{{ $category->articles_count }} {{ Str::plural('article', $category->articles_count) }}</div><div class="flex items-center gap-3"><form method="POST" action="{{ route('support.knowledge.categories.update', $category) }}" class="flex min-w-0 flex-1 gap-2">@csrf @method('PATCH')<input name="name" value="{{ $category->name }}" required maxlength="80" class="min-w-0 flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm"><button class="text-xs font-semibold text-violet-600">Save</button></form><form method="POST" action="{{ route('support.knowledge.categories.delete', $category) }}" onsubmit="return confirm('Delete this category?')">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600">Delete</button></form></div></div>@empty<div class="px-6 py-12 text-center text-sm text-slate-500">No categories yet.</div>@endforelse
        </div></div>
    </div>
</div>
@endsection
